README.md

README was updated in the following sections:
* Importing assets
* Asset methods (Upserting an asset using external ID, Uploading an asset from a file system in a single step)
When reviewing, please make sure to test the code samples as well.

Update README – asset titles

---

KenticoCloud.ContentManagement/ContentManagementClient.cs

This scenario should have been covered by ListAssets_WithContinuation_ListsAllAssets test. However it depends on sufficient amount of assets (more than 100) to be uploaded to the Sample Project. Unfortunatelly I do not have permissions to this project.

DEL-1984 Fixed JSON error in ListAssetsAsync call

---

KenticoCloud.ContentManagement.Tests/ContentManagementHttpClientTests.cs
KenticoCloud.ContentManagement/Modules/Extensions/HttpRequestHeadersExtensions.cs
KenticoCloud.ContentManagement/Modules/HttpClient/ContentManagementHttpClient.cs

Add feature #24 
- [x ] Code follows coding conventions held in this repo
- [x ] Automated tests have been added
- [ x] Tests are passing
Run test 'CorrectSdkVersionHeaderAdded'

Issue 24 add sdk usage header

---

KenticoCloud.ContentManagement.Helpers/KenticoCloud.ContentManagement.Helpers.csproj
KenticoCloud.ContentManagement/KenticoCloud.ContentManagement.csproj
README.md

#7 Enable SourceLink

---

KenticoCloud.ContentManagement.Tests/EndpointUrlBuilderTests.cs

KCL-1564: Some tests are missing asserts in CM API SDK

---

Kentico.Kontent.Management.Helpers.Tests/Kentico.Kontent.Management.Helpers.Tests.csproj
Kentico.Kontent.Management.Tests/Kentico.Kontent.Management.Tests.csproj
Kentico.Kontent.Management.Tests/ManagementClientTests.cs
Kentico.Kontent.Management.Tests/ManagementHttpClientTests.cs
Kentico.Kontent.Management.Tests/Mocks/FileSystemHttpClientMock.cs
Kentico.Kontent.Management.Tests/Modules/ActionInvoker/ActionInvokerTests.cs
Kentico.Kontent.Management.Tests/TestUtils.cs
Kentico.Kontent.Management/Configuration/ManagementOptions.cs
Kentico.Kontent.Management/ManagementClient.cs
Kentico.Kontent.Management/ManagementClientExtensions.cs
Kentico.Kontent.Management/ManagementEndpointUrlBuilderV2.cs
Kentico.Kontent.Management/Models/Assets/AssetFolder.cs
Kentico.Kontent.Management/Models/Assets/AssetFolderHierarchy.cs
Kentico.Kontent.Management/Models/Assets/AssetFolderIdentifier.cs
Kentico.Kontent.Management/Models/Assets/AssetFolderLinkingHierarchy.cs
Kentico.Kontent.Management/Models/Assets/AssetFolderList.cs
Kentico.Kontent.Management/Models/Assets/AssetModel.cs
Kentico.Kontent.Management/Models/Assets/AssetUpdateModel.cs
Kentico.Kontent.Management/Models/Assets/AssetUpsertModel.cs
Kentico.Kontent.Management/Models/Items/ContentItemVariantModel.cs
Kentico.Kontent.Management/Models/ProjectReport/Project.cs
Kentico.Kontent.Management/Modules/ActionInvoker/ActionInvoker.cs
Kentico.Kontent.Management/Modules/ActionInvoker/IActionInvoker.cs
Kentico.Kontent.Management/Modules/ActionInvoker/IMessageCreator.cs
Kentico.Kontent.Management/Modules/ActionInvoker/MessageCreator.cs
Kentico.Kontent.Management/Modules/HttpClient/HttpClient.cs
Kentico.Kontent.Management/Modules/HttpClient/IManagementHttpClient.cs
Kentico.Kontent.Management/Modules/HttpClient/ManagementHttpClient.cs
Kentico.Kontent.Management/Modules/ResiliencePolicy/DefaultResiliencePolicyProvider.cs
README.md

Xantari master

---

Kentico.Kontent.Management.Tests/Data/ListFolders_Qjuq0PLi1K/GET_7NAVt53LQk/request.json
Kentico.Kontent.Management.Tests/Data/ListFolders_Qjuq0PLi1K/GET_7NAVt53LQk/response.json
Kentico.Kontent.Management.Tests/Data/ListFolders_Qjuq0PLi1K/GET_7NAVt53LQk/response_content.json

Add mocked data for skipped ListFolders_GetFolderHierarchy_ExistingFolder test
#60

Add mocked data for ListFolders_GetFolderHierarchy_ExistingFolder test

---

Kentico.Kontent.Management.Tests/ManagementClientTests/TaxonomyGroupTests.cs
Kentico.Kontent.Management.Tests/Unit/Base/FileSystemFixture.cs
Kentico.Kontent.Management.Tests/Unit/CodeSamples/CmApiV2.cs
Kentico.Kontent.Management.Tests/Unit/CodeSamples/ImportingContentModel.cs
Kentico.Kontent.Management.Tests/Unit/Data/TaxonomyGroup/TaxonomyGroup.json
Kentico.Kontent.Management.Tests/Unit/Data/TaxonomyGroup/TaxonomyGroups.json
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/LanguagesTests.cs
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/TaxonomyGroupTests.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/Patch/TaxonomyGroupAddIntoPatchModel.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/TaxonomyBaseModel.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/TaxonomyGroupCreateModel.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/TaxonomyGroupModel.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/TaxonomyTermCreateModel.cs
Kentico.Kontent.Management/Models/TaxonomyGroups/TaxonomyTermModel.cs

Fixes #69
TaxonomyGroup tests moved to the new tests architecture.

Taxonomy group unit tests

---

Kentico.Kontent.Management.Tests/ManagementClientTests/AssetTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/CollectionTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/ContentItemTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/ContentTypeSnippetTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/ContentTypeTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/LanguageVariantTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/ProjectTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/Scenario.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/TaxonomyGroupTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/ValidationTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/WebhookTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/WorkflowStepTests.cs
Kentico.Kontent.Management.Tests/TestUtils.cs
Kentico.Kontent.Management.Tests/Unit/Base/FileSystemFixture.cs
Kentico.Kontent.Management/IManagementClient.cs
Kentico.Kontent.Management/ManagementClient.cs
Kentico.Kontent.Management/ManagementClientExtensions.cs

Fixes #53
Add interface to ManagementClient class.

Add interface to managementClient

---

Kentico.Kontent.Management.Tests/Unit/Data/Webhook/Webhook.json
Kentico.Kontent.Management.Tests/Unit/Data/Webhook/Webhooks.json
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/WebhookTests.cs

Fixes #69
Add unit tests for webhook methods 

add webhook unit tests

---

.github/workflows/integrate.yml
.github/workflows/release.yml
Kentico.Kontent.Management.Helpers.Tests/Kentico.Kontent.Management.Helpers.Tests.csproj
Kentico.Kontent.Management.Helpers/Kentico.Kontent.Management.Helpers.csproj
Kentico.Kontent.Management.Tests/Kentico.Kontent.Management.Tests.csproj
Kentico.Kontent.Management/Kentico.Kontent.Management.csproj

Let's discuss if we want to support `netstandard2.0` to.

Try out multitarget build

---

Kentico.Kontent.Management.Tests/Kentico.Kontent.Management.Tests.csproj
Kentico.Kontent.Management.Tests/Unit/ElementMetadataExtensionTests.cs
Kentico.Kontent.Management/Kentico.Kontent.Management.csproj

Fixes #110 
Add unit tests for ElementMetadataExtension.

Add unit tests for ElementMetadataExtension

---

Kentico.Kontent.Management.Tests/Unit/ElementMetadataExtensionTests.cs
Kentico.Kontent.Management/Models/Types/Elements/ValidationRegexModel.cs

Extend regex validation message

---

Kentico.Kontent.Management.Tests/EndpointUrlBuilderTests.cs
Kentico.Kontent.Management.Tests/ManagementClientTests/AssetTests.cs
Kentico.Kontent.Management.Tests/Unit/CodeSamples/CmApiV2.cs
Kentico.Kontent.Management.Tests/Unit/Data/CodeSamples/ProjectRole.json
Kentico.Kontent.Management.Tests/Unit/Data/CodeSamples/ProjectRoles.json
Kentico.Kontent.Management.Tests/Unit/Data/ProjectRole/ProjectRole.json
Kentico.Kontent.Management.Tests/Unit/Data/ProjectRole/ProjectRoles.json
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/LanguageTests.cs
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/ProjectRoleTests.cs
Kentico.Kontent.Management/IManagementClient.cs
Kentico.Kontent.Management/ManagementClient.cs
Kentico.Kontent.Management/Models/Roles/ProjectRoleModel.cs
Kentico.Kontent.Management/Models/Roles/ProjectRolesModel.cs
Kentico.Kontent.Management/Modules/UrlBuilder/EndpointUrlBuilder.cs
Kentico.Kontent.Management/Modules/UrlBuilder/Templates/ProjectRolesTemplate.cs

Add support for project roles

---

Kentico.Kontent.Management.Tests/ManagementClientTests/LanguageVariantTests.cs
Kentico.Kontent.Management.Tests/Unit/Data/ComplexTestModel.cs
Kentico.Kontent.Management.Tests/Unit/Data/LanguageVariant/LanguageVariant.json
Kentico.Kontent.Management.Tests/Unit/Data/TweetTestModel.cs
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/LanguageVariantTests.cs
Kentico.Kontent.Management/Models/StronglyTyped/LanguageVariantModel.cs
Kentico.Kontent.Management/Modules/ModelBuilders/ModelProvider.cs

Unit tests for language variants - basic cases, will be extended.
And fixed strongly typed model for language variant

Language variants unit test - start

---

Kentico.Kontent.Management.Tests/Unit/Base/FileSystemFixture.cs
Kentico.Kontent.Management.Tests/Unit/Data/Language/LanguagesPage1.json
Kentico.Kontent.Management.Tests/Unit/Data/Language/LanguagesPage2.json
Kentico.Kontent.Management.Tests/Unit/Data/Language/LanguagesPage3.json
Kentico.Kontent.Management.Tests/Unit/ManagementClientTests/LanguageTests.cs
Kentico.Kontent.Management/Extenstions/ListingExtensions.cs
README.md

Fixes #130 
Usage:
`var response = await client.ListLanguagesAsync().GetAllAsync();`

GetAll extension method

---

Kentico.Kontent.Management.Tests/Unit/CodeSamples/CmApiV2.cs

Add missing code samples

---

Kentico.Kontent.Management/Extenstions/ManagementClientExtensions.cs

We don't want these methods in a new version of sdk.

Remove obsolete methods

---

Kentico.Kontent.Management.Tests/Data/CodeSamples/ContentType.json
Kentico.Kontent.Management.Tests/Data/ContentType/ContentTypesPage1.json
Kentico.Kontent.Management/Models/Types/Elements/ElementMetadataBase.cs

- try to create content type with non-localizable element

KCL-8688 - Add non-localizable property to element data model

---

Kentico.Kontent.Management.Tests/Data/ContentType/ContentType.json
Kentico.Kontent.Management.Tests/Data/ContentType/ContentTypesPage1.json
Kentico.Kontent.Management.Tests/Data/ContentType/ContentTypesPage2.json
Kentico.Kontent.Management.Tests/Data/ContentType/ContentTypesPage3.json
Kentico.Kontent.Management.Tests/Data/ContentTypeSnippet/Snippet.json
Kentico.Kontent.Management.Tests/Data/ContentTypeSnippet/SnippetsPage1.json
Kentico.Kontent.Management.Tests/Data/ContentTypeSnippet/SnippetsPage2.json
Kentico.Kontent.Management.Tests/Data/ContentTypeSnippet/SnippetsPage3.json

KCL-8688 - Add NLE parameter into test data

---

Kentico.Kontent.Management.Tests/CodeSamples/CmApiV2.cs
Kentico.Kontent.Management.Tests/Data/CodeSamples/Workflow.json
Kentico.Kontent.Management.Tests/Data/CodeSamples/Workflows.json
Kentico.Kontent.Management.Tests/Data/Workflow/Workflow.json
Kentico.Kontent.Management.Tests/ManagementClientTests/WorkflowTests.cs
Kentico.Kontent.Management/IManagementClient.cs
Kentico.Kontent.Management/ManagementClient.Workflow.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowArchivedStepUpsertModel.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowPublishedStepUpsertModel.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowScopeUpsertModel.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowStepTransitionToUpsertModel.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowStepUpsertModel.cs
Kentico.Kontent.Management/Models/Workflow/WorkflowUpsertModel.cs

[#159] - Insert and Update workflow SDK support

---

Kentico.Kontent.Management.Tests/Modules/Extensions/DynamicExtensionsTests.cs
Kentico.Kontent.Management.Tests/Modules/ModelBuilders/ElementReferenceTests.cs
Kentico.Kontent.Management/Extensions/DynamicExtensions.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/AssetElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/BaseElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/CustomElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/DateTimeElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/LinkedItemsElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/MultipleChoiceElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/NumberElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/RichTextElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/SubpagesElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/TaxonomyElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/TextElement.cs
Kentico.Kontent.Management/Models/LanguageVariants/Elements/UrlSlugElement.cs
Kentico.Kontent.Management/Models/Shared/Reference.cs
Kentico.Kontent.Management/Modules/ModelBuilders/ElementModelProvider.cs

Which issue does this fix? Fixes #172

expose ToElement method from ElementModelProvider

---

Kontent.Ai.Management.Helpers/Kontent.Ai.Management.Helpers.csproj
Kontent.Ai.Management/Kontent.Ai.Management.csproj

Set projects' readme and icon

---

.github/workflows/release.yml

Related to https://github.com/kontent-ai/delivery-sdk-net/issues/292

Unify back the release process

---

Kontent.Ai.Management.Tests/ManagementClientTests/CollectionTests.cs
Kontent.Ai.Management.Tests/ManagementClientTests/LanguageVariantTests.cs

Collection tests

---

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs
Kontent.Ai.Management.Tests/Data/CodeSamples/AsyncValidationTask.json
Kontent.Ai.Management.Tests/Data/CodeSamples/AsyncValidationTaskIssues.json

Code samples for validation endpoint

---

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs
Kontent.Ai.Management.Tests/CodeSamples/ImportContentModel.cs
Kontent.Ai.Management.Tests/Data/ContentType/ContentType.json
Kontent.Ai.Management.Tests/ManagementClientTests/ContentTypeTests.cs
Kontent.Ai.Management/Models/Shared/AssetWithRenditionsReference.cs
Kontent.Ai.Management/Models/Types/Elements/AssetDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/AssetElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/DateTimeElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/AssetDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/DateElementDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/ElementDefaultValue.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/LinkedItemsDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/MultipleChoiceDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/NumberElementDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/TaxonomyElementDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/DefaultValues/TextElementDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/LinkedItemsDefaultValueModel.cs
Kontent.Ai.Management/Models/Types/Elements/LinkedItemsElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/MultipleChoiceElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/NumberElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/TaxonomyElementMetadataModel.cs
Kontent.Ai.Management/Models/Types/Elements/TextElementMetadataModel.cs
Kontent.Ai.Management/Modules/ActionInvoker/AssetWithRenditionsReferenceConverter.cs

https://github.com/kontent-ai/management-sdk-net/issues/201
Should not be merged before release of default values for affected elements. Specific date will be provided here once known. If in doubt contact @Iorethan.

201 - support for_default values in modular content and asset elements

---

Kontent.Ai.Management.Tests/Modules/Extensions/PropertyInfoExtensionsTests.cs
Kontent.Ai.Management/Modules/Extensions/PropertyInfoExtensions.cs
README.md

Which issue does this fix? Fixes #210 

210 introduce GetKontentElementCodename extension method

---

Kontent.Ai.Management.Tests/Kontent.Ai.Management.Tests.csproj
Kontent.Ai.Management.Tests/Modules/Extensions/HttpRequestHeadersExtensionsTests.cs
Kontent.Ai.Management/Attributes/SourceTrackingHeaderAttribute.cs
Kontent.Ai.Management/Modules/ActionInvoker/MessageCreator.cs
Kontent.Ai.Management/Modules/Extensions/HttpRequestHeadersExtensions.cs
README.md

Which issue does this fix? Fixes #197 
Add support for X-KC-SDKID
Please test this for the model generator in self-contained mode. I expect that it might be problematic.

Add support for X-KC-SDKID

---

Kontent.Ai.Management.Tests/ManagementClientTests/ProjectRoleTests.cs

New unit tests for project roles.

project roles new unit tests

---

Kontent.Ai.Management.Tests/ManagementClientTests/WebhookTests.cs

new unit tests for webhooks

---

Kontent.Ai.Management.Tests/ManagementClientTests/ContentTypeTests.cs
Kontent.Ai.Management.Tests/ManagementClientTests/ProjectUserTests.cs
Kontent.Ai.Management/ManagementClient.ProjectUser.cs

New unit tests for project users

project user tests

---

Kontent.Ai.Management.Tests/Data/Subscription/ProjectsPage1.json
Kontent.Ai.Management.Tests/Data/Subscription/ProjectsPage2.json
Kontent.Ai.Management.Tests/Data/Subscription/ProjectsPage3.json
Kontent.Ai.Management.Tests/Data/Subscription/UsersPage1.json
Kontent.Ai.Management.Tests/Data/Subscription/UsersPage2.json
Kontent.Ai.Management.Tests/Data/Subscription/UsersPage3.json
Kontent.Ai.Management.Tests/ManagementClientTests/SubscriptionTests.cs

New unit tests for the subscription.

new subscription tests

---

Kontent.Ai.Management.Tests/Data/Space/ModifySpace_Replace_ModifiesSpace.json
Kontent.Ai.Management.Tests/Data/Space/Space.json
Kontent.Ai.Management.Tests/Data/Space/Spaces.json
Kontent.Ai.Management.Tests/ManagementClientTests/SpaceTests.cs
Kontent.Ai.Management/Models/Spaces/Patch/PropertyName.cs
Kontent.Ai.Management/Models/Spaces/Patch/SpaceOperationReplaceModel.cs
Kontent.Ai.Management/Models/Spaces/SpaceCreateModel.cs
Kontent.Ai.Management/Models/Spaces/SpaceModel.cs

Fixes #233 
not needed
The feature will be released on 29.03.2023

#233 Add root item to Spaces

---

Kontent.Ai.Management.Tests/ManagementClientTests/SpaceTests.cs
Kontent.Ai.Management/ManagementClient.Space.cs

new tests for spaces

---

Kontent.Ai.Management.Tests/Data/Workflow/Workflow.json
Kontent.Ai.Management.Tests/Data/Workflow/Workflows.json
Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs
Kontent.Ai.Management/Models/Workflow/WorkflowArchivedStepModel.cs
Kontent.Ai.Management/Models/Workflow/WorkflowModel.cs
Kontent.Ai.Management/Models/Workflow/WorkflowPublishedStepModel.cs
Kontent.Ai.Management/Models/Workflow/WorkflowScheduledStepModel.cs

Scheduled workflow step was added to the MAPI v2 - this change reflects that. 
(I have also clarified the predefined step summaries and updated tests a bit)
No need for manual testing

Update workflow response model

---

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs
Kontent.Ai.Management.Tests/ManagementClientTests/LanguageVariantTests.cs
Kontent.Ai.Management/IManagementClient.cs
Kontent.Ai.Management/ManagementClient.LanguageVariant.cs
Kontent.Ai.Management/Modules/UrlBuilder/EndpointUrlBuilder.cs

EN-137 - Add access to published content

---

Kontent.Ai.Management/Models/LanguageVariants/LanguageVariantUpsertModel.cs

Which issue does this fix? Fixes #280 

add missing decorators to LanguageVariantUpsertModel
