KenticoCloud.ContentManagement/Models/Items/ContentItemUpdateModel.cs
Constructors of ContentItemUpdateModel were internal therefore it was unable to use this model based on the docs.
=> CMP-580 - Fixed accessibility of ctor of ContentItemUpdateModel

KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs, KenticoCloud.ContentManagement.Tests/Mocks/FileSystemHttpClientMock.cs
The [AppContext.BaseDirectory](https://github.com/mellinoe/ge/issues/2) might return other than the project's root folder. Retrieving of test assets might fail.
Make the code aligned with https://github.com/Kentico/delivery-sdk-net/commit/aa62e70f4e00cff1bebcaebd68c994913a78c3d7#diff-8282cff8647d4e2e2fc87e28e571c6a7 .
=> Unify methods of resolving app's base folder among repos

KenticoCloud.ContentManagement.Tests/ContentManagementHttpClientTests.cs, KenticoCloud.ContentManagement.Tests/Modules/Extensions/HttpRequestHeadersExtensionsTests.cs
Which issue does this fix?
Extend tests to cover that `SendAsync` method adds tracking header.
Check that all test are passing (part of the merge automatic check).
=> Tracking header test

KenticoCloud.ContentManagement.Tests/Modules/ActionInvoker/ActionInvokerTests.cs, KenticoCloud.ContentManagement/Modules/ActionInvoker/ActionInvoker.cs, KenticoCloud.ContentManagement/Modules/ActionInvoker/DecimalObjectConverter.cs
`DecimalObjectConverter` was created and used in `_serializeSettings` of `ActionInvoker` to create workaround for API not being able to accept decimal `0.0`.
Fixes #29
Should be covered with automated test.
=> Issue 29 fix

KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs
=> Switch the order of parameters in Assert.Equal function

KenticoCloud.ContentManagement.Tests/EndpointUrlBuilderTests.cs, KenticoCloud.ContentManagement/ContentManagementEndpointUrlBuilder.cs
Which issue does this fix? Fixes #27 
- By calling the controller, verify that a content item and asset with a slash in the external ID is really created/updated.
- Create a content item via rest API using external id with a slash, then try to update the same content item via the controller, using the same external id
=> DEL-2063 - Allow slashes in external ids

KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs, KenticoCloud.ContentManagement.Tests/Data/CreateAsset_3NJwu6QYJN/POST_2cOMZAbM8a/response_content.json, KenticoCloud.ContentManagement.Tests/Data/CreateAsset_Vmhhwfhm5l/POST_s_isjmStHn/response_content.json, KenticoCloud.ContentManagement.Tests/Data/CreateAsset__KW1FA4lVJ/POST_AGis8GuB6r/response_content.json, KenticoCloud.ContentManagement.Tests/Data/UpsertAssetByExternalId_DuRHOxHJmO/PUT_bYTQwEJQv1/response_content.json, KenticoCloud.ContentManagement.Tests/Data/UpsertAssetByExternalId_ThZdnYABq8/PUT_FyOVYVdXZL/response_content.json, KenticoCloud.ContentManagement/Models/Assets/AssetModel.cs
Return the new property (binary file URL) that was added to the asset response model.
Try to list/get/create/update an asset, the returned model should contain the correct asset URL.
=> KCL-2816 - add a binary file url to the asset response model

Kentico.Kontent.Management.Tests/ManagementClientTests.cs, Kentico.Kontent.Management.Tests/Mocks/FileSystemHttpClientMock.cs, Kentico.Kontent.Management.Tests/Modules/ActionInvoker/ActionInvokerTests.cs, Kentico.Kontent.Management.Tests/TestUtils.cs, Kentico.Kontent.Management/Configuration/ManagementOptions.cs, Kentico.Kontent.Management/ManagementClient.cs, Kentico.Kontent.Management/ManagementClientExtensions.cs, Kentico.Kontent.Management/ManagementEndpointUrlBuilderV2.cs, Kentico.Kontent.Management/Models/Assets/AssetFolder.cs, Kentico.Kontent.Management/Models/Assets/AssetFolderHierarchy.cs, Kentico.Kontent.Management/Models/Assets/AssetFolderIdentifier.cs, Kentico.Kontent.Management/Models/Assets/AssetFolderLinkingHierarchy.cs, Kentico.Kontent.Management/Models/Assets/AssetFolderList.cs, Kentico.Kontent.Management/Models/Assets/AssetModel.cs, Kentico.Kontent.Management/Models/Assets/AssetUpdateModel.cs, Kentico.Kontent.Management/Models/Assets/AssetUpsertModel.cs, Kentico.Kontent.Management/Modules/ActionInvoker/ActionInvoker.cs, Kentico.Kontent.Management/Modules/ActionInvoker/IActionInvoker.cs, Kentico.Kontent.Management/Modules/ActionInvoker/IMessageCreator.cs, Kentico.Kontent.Management/Modules/ActionInvoker/MessageCreator.cs, Kentico.Kontent.Management/Modules/HttpClient/IManagementHttpClient.cs, Kentico.Kontent.Management/Modules/HttpClient/ManagementHttpClient.cs, README.md
Which issue does this fix? 
This is a partial fix for #50. It transfers most asset V1 API interactions that existed to the V2 API and adds the Folder Listing API method. It is not a complete Asset V1 -> V2 API conversion however as it is missing these functions:
https://docs.kontent.ai/reference/management-api-v2#operation/add-asset-folders
https://docs.kontent.ai/reference/management-api-v2#operation/modify-asset-folders
https://docs.kontent.ai/reference/management-api-v2#operation/upload-a-binary-file (this one is still using the V1 API endpoint)
- Sort of: tests need request/response static captures from Kentico's internal only project site to fit the testing scenarios. I did not include any live site data request/response captures.
- Sort of: The new tests only work against my live …
=> Asset API V1 to V2 API Transition

Kentico.Kontent.Management.Tests/Unit/CodeSamples/CmApiV2.cs, Kentico.Kontent.Management.Tests/Unit/Data/CodeSamples/AssetRendition.json, Kentico.Kontent.Management.Tests/Unit/Data/CodeSamples/AssetRenditions.json
#137
The code samples were added into the docu here: https://github.com/KenticoDocs/kontent-docs-samples/commit/cd533f450e58293283d9c0167e4b1d8a1db3dd74
No testing required
=> Add renditions docu code samples into unit tests

Kontent.Ai.Management.Tests/Data/CodeSamples/ContentType.json, Kontent.Ai.Management.Tests/Data/CodeSamples/ContentTypes.json, Kontent.Ai.Management.Tests/Data/CodeSamples/PatchContentTypeResponse.json, Kontent.Ai.Management/Models/Types/Elements/RichTextTextBlockType.cs
Which issue does this fix? Fixes #`KCL-9407`
We have added support for H5 and H6 in MAPI for rich text element.
Modify RT element in CT. Set some limitations.
- Check, that H5 and H6 are present in `RichTextElementMetadataModel.AllowedTextBlocks`
- If CT contains rte with some limitations and H5/H6 are allowed, it is possible to read this CT via `GetContentTypeAsync` method.
=> KCL-9407 - add support for H5 and H6

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs, Kontent.Ai.Management.Tests/CodeSamples/Readme.cs, Kontent.Ai.Management.Tests/Data/Asset/Asset.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage1.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage2.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage3.json, Kontent.Ai.Management.Tests/Data/CodeSamples/Readme/ArticleLanguageVariantResponse.json, Kontent.Ai.Management.Tests/Data/CodeSamples/Readme/ArticleLanguageVariantUpdatedResponse.json, Kontent.Ai.Management.Tests/Data/ElementsData.cs, Kontent.Ai.Management.Tests/Data/LanguageVariant/LanguageVariant.json, Kontent.Ai.Management.Tests/Data/LanguageVariant/LanguageVariants.json, Kontent.Ai.Management.Tests/Data/LanguageVariant/LanguageVariantsPage1.json, Kontent.Ai.Management.Tests/Data/LanguageVariant/LanguageVariantsPage2.json, Kontent.Ai.Management.Tests/Data/LanguageVariant/LanguageVariantsPage3.json, Kontent.Ai.Management.Tests/Modules/ModelBuilders/ElementModelProviderTests.cs, Kontent.Ai.Management/Models/LanguageVariants/Elements/BaseElement.cs, Kontent.Ai.Management/Models/LanguageVariants/Elements/DateTimeElement.cs, Kontent.Ai.Management/Models/Workflow/ScheduleModel.cs
Which issue does this fix? Fixes #KCL-9004`
A new property "displayTimeZone" was added to DateTime element which affects following MAPI endpoints:
- Publish or schedule a language variant
- Unpublish or schedule unpublishing of a language variant
- Upsert a language variant
The changes needs to be reflected in the MAPI v2 docs + code samples and SDK
All operations should be covered in tests.
The code samples changes merge request:
https://github.com/Kontent-ai-Learn/kontent-ai-learn-code-samples/pull/60
=> Add support for displayTimeZone of DateTime element

Kontent.Ai.Management.Tests/Data/ContentType/ContentType.json, Kontent.Ai.Management.Tests/Data/ContentType/ContentTypesPage2.json, Kontent.Ai.Management.Tests/Data/ContentTypeSnippet/Snippet.json, Kontent.Ai.Management.Tests/Data/ContentTypeSnippet/SnippetsPage1.json, Kontent.Ai.Management.Tests/Data/ContentTypeSnippet/SnippetsPage2.json, Kontent.Ai.Management.Tests/Data/ContentTypeSnippet/SnippetsPage3.json, Kontent.Ai.Management/Models/Types/Elements/AssetElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/CustomElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/DateTimeElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/ElementMetadataBase.cs, Kontent.Ai.Management/Models/Types/Elements/LinkedItemsElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/MultipleChoiceElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/NumberElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/RichTextElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/SubpagesElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/TaxonomyElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/TextElementMetadataModel.cs, Kontent.Ai.Management/Models/Types/Elements/UrlSlugElementMetadataModel.cs
Which issue does this fix? Fixes #`KCL-9904`
We decided to remove `IsNonLocalizable` property from all type elements which are not supported and will not be supported in the future before we release this feature publicly in December (currently this feature is in early access). The type elements that should not have this property are snippet element and guidelines element.
After discussion with @Simply007 we decided that this can be released as a new minor version because non-localizable elements are still in early access. But we can discuss it further if you think it should be considered a breaking change and released as a new major version.
=> KCL-9904 Remove is_non_localizable property from unsupported type elements in MAPI

Kontent.Ai.Management.Tests/ManagementHttpClientTests.cs, Kontent.Ai.Management/Exceptions/ManagementException.cs, Kontent.Ai.Management/Kontent.Ai.Management.csproj, Kontent.Ai.Management/Modules/HttpClient/ManagementHttpClient.cs, Kontent.Ai.Management/Modules/ResiliencePolicy/DefaultResiliencePolicyProvider.cs
Fixes #211 
Improve overall default retry policy. It only worked for responses from MAPI, but it did not take into account that an exception can be thrown. 
Unit tests added.
=> fix retry policy

Kontent.Ai.Management.Tests/ManagementClientTests/LanguageVariantTests.cs, Kontent.Ai.Management.Tests/ManagementClientTests/WorkflowTests.cs, Kontent.Ai.Management/ManagementClient.Workflow.cs
new unit test for workflow
Breaking changes:
`CreateWorkflowAsync` now throws if create model is null
`UpdateWorkflowAsync` now throws if identifier or upsert model is null
`SchedulePublishingOfLanguageVariantAsync` now throws if schedule model is null
`ScheduleUnpublishingOfLanguageVariantAsync` now throws if schedule model is null
=> new workflow tests

Kontent.Ai.Management.Tests/Data/Asset/Asset.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage1.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage2.json, Kontent.Ai.Management.Tests/Data/Asset/AssetsPage3.json, Kontent.Ai.Management.Tests/ManagementClientTests/AssetRenditionTests.cs, Kontent.Ai.Management.Tests/ManagementClientTests/AssetTests.cs, Kontent.Ai.Management.Tests/Modules/UrlBuilder/AssetRenditionTests.cs, Kontent.Ai.Management.Tests/Modules/UrlBuilder/AssetTests.cs, Kontent.Ai.Management/Models/Assets/AssetCreateModel.cs, Kontent.Ai.Management/Models/Assets/AssetModel.cs, Kontent.Ai.Management/Models/Assets/AssetUpsertModel.cs, Kontent.Ai.Management/Models/StronglyTyped/AssetCreateModel.cs, Kontent.Ai.Management/Models/StronglyTyped/AssetModel.cs, Kontent.Ai.Management/Models/StronglyTyped/AssetUpsertModel.cs, Kontent.Ai.Management/Modules/ModelBuilders/ModelProvider.cs, Kontent.Ai.Management/Modules/UrlBuilder/Templates/AssetTemplate.cs
Which issue does this fix? Fixes #249
=> Add asset codename

Kontent.Ai.Management.Tests/Data/ContentItem/ContentItem.json, Kontent.Ai.Management.Tests/Data/ContentItem/ContentItemPage1.json, Kontent.Ai.Management.Tests/Data/ContentItem/ContentItemPage2.json, Kontent.Ai.Management.Tests/Data/ContentItem/ContentItemPage3.json, Kontent.Ai.Management.Tests/Data/Space/ModifySpace_Replace_ModifiesSpace.json, Kontent.Ai.Management.Tests/Data/Space/Space.json, Kontent.Ai.Management.Tests/ManagementClientTests/LanguageVariantTests.cs, Kontent.Ai.Management.Tests/ManagementClientTests/SpaceTests.cs, Kontent.Ai.Management/IManagementClient.cs, Kontent.Ai.Management/ManagementClient.LanguageVariant.cs, Kontent.Ai.Management/ManagementClient.Space.cs, Kontent.Ai.Management/Models/Items/ContentItemModel.cs, Kontent.Ai.Management/Models/Spaces/Patch/PropertyName.cs, Kontent.Ai.Management/Models/Spaces/SpaceCreateModel.cs, Kontent.Ai.Management/Models/Spaces/SpaceModel.cs, Kontent.Ai.Management/Modules/UrlBuilder/EndpointUrlBuilder.cs, README.md
Fixes #255
Manually call the new methods and verify the results
=> #255 add collections to spaces

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs, Kontent.Ai.Management.Tests/Data/CodeSamples/PostWebhookResponse.json, Kontent.Ai.Management.Tests/Data/CodeSamples/Webhook.json, Kontent.Ai.Management.Tests/Data/CodeSamples/Webhooks.json, Kontent.Ai.Management.Tests/Data/Webhook/Webhook.json, Kontent.Ai.Management.Tests/Data/Webhook/Webhooks.json, Kontent.Ai.Management.Tests/ManagementClientTests/WebhookTests.cs, Kontent.Ai.Management/Models/Webhooks/CustomHeaderModel.cs, Kontent.Ai.Management/Models/Webhooks/WebhookCreateModel.cs, Kontent.Ai.Management/Models/Webhooks/WebhookModel.cs
Enable customers to enhance webhook notifications with custom headers. Do not release before Feb 21, 2024.
=> Add custom headers to webhooks

Kontent.Ai.Management.Tests/CodeSamples/CmApiV2.cs, Kontent.Ai.Management.Tests/ManagementClientTests/ContentTypeSnippetTests.cs, Kontent.Ai.Management.Tests/ManagementClientTests/ContentTypeTests.cs, Kontent.Ai.Management.Tests/ManagementClientTests/TaxonomyGroupTests.cs, Kontent.Ai.Management/Models/AssetFolders/Patch/AssetFolderAddIntoModel.cs, Kontent.Ai.Management/Models/TaxonomyGroups/Patch/TaxonomyGroupAddIntoPatchModel.cs, Kontent.Ai.Management/Models/TaxonomyGroups/Patch/TaxonomyGroupMovePatchModel.cs, Kontent.Ai.Management/Models/TypeSnippets/Patch/ContentTypeSnippetAddIntoPatchModel.cs, Kontent.Ai.Management/Models/TypeSnippets/Patch/ContentTypeSnippetPatchMoveModel.cs, Kontent.Ai.Management/Models/Types/Patch/ContentTypeAddIntoPatchModel.cs, Kontent.Ai.Management/Models/Types/Patch/ContentTypeMovePatchModel.cs
Add support for new move operation in content type, snippet and taxonomy PATCH endpoints.
=> Add move operation to type, snippet and taxonomy PATCH

Kontent.Ai.Management.Tests/Data/AssetFolder/Folder.json, Kontent.Ai.Management.Tests/ManagementClientTests/AssetFolderTests.cs, Kontent.Ai.Management/Extensions/AssetExtensions.cs, Kontent.Ai.Management/Models/AssetFolders/AssetFolderHierarchy.cs, Kontent.Ai.Management/Models/AssetFolders/AssetFolderLinkingHierarchy.cs
Adding support for asset folder codenames, so assets can be inserted into specific folder, referenced by its codename.
Try getting / adding asset folders with codenames, adding asset to a folder referenced by codename.
=> EN-207 Add asset folder codenames

Kontent.Ai.Management/Models/Types/Elements/TaxonomyElementMetadataModel.cs
Fixes #268 
adds missing `name` property to `TaxonomyElementMetaDataModel`
=> add name property to taxonomy element

Kontent.Ai.Management.Tests/Data/CustomApp/CustomApp.json, Kontent.Ai.Management.Tests/Data/CustomApp/CustomAppsPage1.json, Kontent.Ai.Management.Tests/Data/CustomApp/CustomAppsPage2.json, Kontent.Ai.Management.Tests/Data/CustomApp/CustomAppsPage3.json, Kontent.Ai.Management.Tests/Data/CustomApp/ModifyCustomApp_AddInto_ModifiesCustomApp.json, Kontent.Ai.Management.Tests/Data/CustomApp/ModifyCustomApp_Remove_ModifiesCustomApp.json, Kontent.Ai.Management.Tests/Data/CustomApp/ModifyCustomApp_Replace_ModifiesCustomApp.json, Kontent.Ai.Management.Tests/Kontent.Ai.Management.Tests.csproj, Kontent.Ai.Management.Tests/ManagementClientTests/CustomAppTests.cs, Kontent.Ai.Management/IManagementClient.cs, Kontent.Ai.Management/ManagementClient.AssetFolder.cs, Kontent.Ai.Management/ManagementClient.Collection.cs, Kontent.Ai.Management/ManagementClient.ContentType.cs, Kontent.Ai.Management/ManagementClient.ContentTypeSnippet.cs, Kontent.Ai.Management/ManagementClient.CustomApp.cs, Kontent.Ai.Management/ManagementClient.Environment.cs, Kontent.Ai.Management/ManagementClient.Language.cs, Kontent.Ai.Management/ManagementClient.TaxonomyGroup.cs, Kontent.Ai.Management/Models/CustomApps/CustomAppCreateModel.cs, Kontent.Ai.Management/Models/CustomApps/CustomAppListingResponseServerModel.cs, Kontent.Ai.Management/Models/CustomApps/CustomAppModel.cs, Kontent.Ai.Management/Models/CustomApps/Patch/CustomAppAddIntoPatchModel.cs, Kontent.Ai.Management/Models/CustomApps/Patch/CustomAppOperationBaseModel.cs, Kontent.Ai.Management/Models/CustomApps/Patch/CustomAppRemovePatchModel.cs, Kontent.Ai.Management/Models/CustomApps/Patch/CustomAppReplacePatchModel.cs, Kontent.Ai.Management/Models/CustomApps/Patch/PropertyName.cs, Kontent.Ai.Management/Modules/UrlBuilder/EndpointUrlBuilder.cs, Kontent.Ai.Management/Modules/UrlBuilder/Templates/CustomAppTemplate.cs
As a part of new feature Custom Apps we are adding MAPI support as well.
=> EN-326 Add Custom Apps support via Management Api

Kontent.Ai.Management.Tests/ManagementClientTests/PublishingTests.cs, Kontent.Ai.Management/IManagementClient.cs, Kontent.Ai.Management/ManagementClient.Publishing.cs, Kontent.Ai.Management/Models/Publishing/SchedulePublishAndUnpublishModel.cs, Kontent.Ai.Management/Modules/UrlBuilder/EndpointUrlBuilder.cs
=> EN-261 Add schedule publish and unpublish endpoint to Management API SDK

Kontent.Ai.Management/ManagementClient.cs, Kontent.Ai.Management/Modules/HttpClient/HttpClient.cs, Kontent.Ai.Management/Modules/ModelBuilders/ElementModelProvider.cs, Kontent.Ai.Management/Modules/ModelBuilders/IElementModelProvider.cs
Fixes #270 #252 
Adds overloaded constructor to `ManagementClient` accepting a custom `HttpClient` object. Adjusts internal logic to propagate custom client to `ManagementHttpClient`. Also makes `ElementModelProvider` public for convenience (requested several times).
=> Add support for custom HTTP client, make ElementModelProvider public
